#!/usr/bin/env node
//
// Extracts the per-code-year enum sets the editor needs from CBECC's own
// "Input Data Model" dumps, so the tables in CIBD_editor.html are derived from the
// shipped ruleset rather than transcribed by hand.
//
//   node tools/extract_ruleset_enums.js            # print the JS tables to stdout
//   node tools/extract_ruleset_enums.js --check    # exit 1 if the editor disagrees
//
// The data models are NOT in this repo -- they ship with each CBECC install, under
//   <CBECC 20xx Data>/Documents/RulesetSource/*Input Data Model.txt
// Point DATA_ROOT at the folder holding the "CBECC <year> Data" directories, or set
// the CBECC_DATA_ROOT environment variable. When a year's model isn't present the
// script skips that year and says so, rather than silently emitting a short table.
//
// Why this exists: a diff of the 2022 and 2025 models found 36 of 39 watched enum
// sets byte-identical, so the year-to-year delta is small -- but it is not zero
// (ZnSys:Type gained EvaporativeCooler in 2025, AirSys:ClgCtrl lost three options),
// and nothing else in the build would notice a new ruleset changing one.

const fs = require('fs');
const path = require('path');

const DATA_ROOT = process.env.CBECC_DATA_ROOT ||
  "C:/Users/CharlieChristenson/OneDrive - Stok LLC/Documents";

// Where each year's Input Data Model lives, relative to DATA_ROOT.
const MODEL_PATHS = {
  2022: "CBECC 2022 Data/Documents/RulesetSource/T24N_2022 - Input Data Model.txt",
  2025: "CBECC 2025 Data/Documents/RulesetSource/T24_2025 - Input Data Model.txt",
  // 2028: add when CEC ships it.
};

// The enum sets the editor gates behavior on. Keep in sync with what CIBD_editor.html
// actually consumes -- an entry here that the editor ignores is just noise.
const WANTED = [
  ['AirSys', 'Type'],
  ['ZnSys',  'Type'],
];

// The data model is a flat text dump:
//   <Object>  <LongName>  #Props:n/m        <- column 0
//         <Prop>   <LongName>  <DataType>   <- indented 6
//                   3:  "Value"             <- enum values, deeper
// Conditional blocks ("When: X = ...") re-list values per condition; we union them,
// which is what "every value this property can legally take" means for our purposes.
function parseModel(file){
  const lines = fs.readFileSync(file, 'latin1').split(/\r?\n/);
  const objs = {};
  let obj = null, prop = null;
  for(const line of lines){
    const om = line.match(/^([A-Za-z][A-Za-z0-9_]*)\s+\S.*#Props:/);
    if(om){ obj = om[1]; objs[obj] = objs[obj] || {}; prop = null; continue; }
    if(!obj) continue;
    const pm = line.match(/^ {6}([A-Za-z][A-Za-z0-9_]*)\s{2,}\S/);
    if(pm){ prop = pm[1]; objs[obj][prop] = objs[obj][prop] || []; continue; }
    if(!prop) continue;
    const vm = line.match(/^\s+-?\d+:\s+"(.*)"\s*$/);
    if(vm && objs[obj][prop].indexOf(vm[1]) === -1) objs[obj][prop].push(vm[1]);
  }
  return objs;
}

// "- specify -" is CBECC's own placeholder for "user hasn't chosen yet", not a Type.
const isPlaceholder = v => /^- .* -$/.test(v);

function collect(){
  const out = {};
  for(const [year, rel] of Object.entries(MODEL_PATHS)){
    const file = path.join(DATA_ROOT, rel);
    if(!fs.existsSync(file)){
      console.error(`# skipped ${year}: not found at ${file}`);
      continue;
    }
    const model = parseModel(file);
    const per = {};
    for(const [o, p] of WANTED){
      const vals = (model[o] && model[o][p]) || null;
      if(!vals){ console.error(`# warning: ${year} has no ${o}:${p}`); continue; }
      per[o + ':' + p] = vals.filter(v => !isPlaceholder(v));
    }
    out[year] = per;
  }
  return out;
}

function emit(data){
  const years = Object.keys(data).sort();
  console.log('// GENERATED by tools/extract_ruleset_enums.js -- do not edit by hand.');
  console.log('// Source: CBECC "<year> - Input Data Model.txt", one per installed ruleset.');
  console.log('// Regenerate after any CBECC ruleset update; test_code_year.js checks these');
  console.log('// against the installed models when they are available.');
  console.log('const RULESET_SYSTEM_TYPES = {');
  for(const y of years){
    const d = data[y];
    console.log(`  ${y}: {`);
    console.log(`    AirSys: ${JSON.stringify(d['AirSys:Type'] || [])},`);
    console.log(`    ZnSys:  ${JSON.stringify(d['ZnSys:Type']  || [])},`);
    console.log('  },');
  }
  console.log('};');
}

function check(data){
  const src = fs.readFileSync(path.join(__dirname, '..', 'CIBD_editor.html'), 'utf8');
  const m = src.match(/const RULESET_SYSTEM_TYPES = (\{[\s\S]*?\n\});/);
  if(!m){ console.error('FAIL: RULESET_SYSTEM_TYPES not found in CIBD_editor.html'); process.exit(1); }
  // eslint-disable-next-line no-eval
  const inEditor = eval('(' + m[1] + ')');
  let bad = 0;
  for(const [year, d] of Object.entries(data)){
    const got = inEditor[year];
    if(!got){ console.error(`FAIL: editor has no entry for ${year}`); bad++; continue; }
    for(const fam of ['AirSys', 'ZnSys']){
      const want = d[fam + ':Type'] || [];
      const have = got[fam] || [];
      const missing = want.filter(v => have.indexOf(v) === -1);
      const extra   = have.filter(v => want.indexOf(v) === -1);
      if(missing.length || extra.length){
        bad++;
        console.error(`FAIL ${year} ${fam}:` +
          (missing.length ? ` missing [${missing}]` : '') +
          (extra.length   ? ` unexpected [${extra}]` : ''));
      }
    }
  }
  if(bad){ console.error(`\n${bad} mismatch(es) -- regenerate with: node tools/extract_ruleset_enums.js`); process.exit(1); }
  console.log(`OK: editor tables match the installed data models (${Object.keys(data).join(', ')})`);
}

const data = collect();
if(Object.keys(data).length === 0){
  console.error('No data models found. Set CBECC_DATA_ROOT to the folder containing the "CBECC <year> Data" directories.');
  process.exit(2);
}
if(process.argv.includes('--check')) check(data); else emit(data);
